namespace DemoViewer.NET.Extensions.Loading;

/// <summary>
///     This project's extension-signing public keys: SubjectPublicKeyInfo, base64, ECDSA P-256
///     (strat-book-plugin.md §7.9). A directory's <c>extension.sig</c> is trusted if it verifies against
///     ANY key here, so rotation adds the new key ahead of removing the old one rather than replacing it
///     outright. Generated by <c>tools/extension-signing</c> (<c>keygen</c>); the matching private key is
///     not in this repo (see §7.9).
/// </summary>
public static class PublisherKeys
{
    /// <summary>Generated 2026-10-03, key id dfe4ae3ebb28794fb79a03562ad36eaf252ebe1753292574e752bad4bc1c4cc0.</summary>
    public const string Primary = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESNpQSAWXkLBpiiAxcMYjd8ABZhPlNjPH5kKh11h7pgFAroGy0GgaQMgZrMb9Weex2kA8+Ft6y9MuHo7uzhmJog==";

    /// <summary>Every key a signature may verify against. One entry today; see <see cref="Primary" />.</summary>
    public static IReadOnlyList<string> Current { get; } = [Primary];
}
