#region

using System.Text.Json;

#endregion

namespace Cs2DemoKit.Analysis.Catalog;

/// <summary>
///     Loads the embedded rules catalog (<c>rules/catalog.json</c>, generated by
///     tools/DemoViewer.NET.RulesCatalog and drift-gated in CI). Runtime consumers — the data
///     browser, load-time enum validation, the <c>rules check</c> CLI — read this instead of
///     probing the filesystem, so they always see the catalog their build shipped with.
/// </summary>
public static class CatalogResource
{
    private const string ResourceName = "Cs2DemoKit.Analysis.Catalog.catalog.json";

    private static readonly Lazy<CatalogRoot> _cached = new(LoadCore);

    private static readonly JsonSerializerOptions _options = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <summary>The embedded catalog, parsed once per process.</summary>
    public static CatalogRoot Load() => _cached.Value;

    private static CatalogRoot LoadCore()
    {
        using Stream stream = typeof(CatalogResource).Assembly.GetManifestResourceStream(ResourceName)
                              ?? throw new InvalidOperationException(
                                  $"embedded catalog resource '{ResourceName}' missing from "
                                  + $"{typeof(CatalogResource).Assembly.GetName().Name}. A released build always "
                                  + "carries it, so this is a broken or hand-assembled assembly; from a Cs2DemoKit "
                                  + "source tree, regenerate it with the rules-catalog tool "
                                  + "(tools/DemoViewer.NET.RulesCatalog) and rebuild.");
        return JsonSerializer.Deserialize<CatalogRoot>(stream, _options)
               ?? throw new InvalidOperationException("embedded catalog deserialized to null");
    }
}
