#region

using System.Text.Json;
using System.Text.Json.Nodes;
using Cs2DemoKit.Analysis.Catalog;

#endregion

namespace DemoViewer.NET.RulesCatalog;

/// <summary>
///     Generates the shipped <c>rules/dv-rules.schema.json</c> — the
///     JSON schema for v2 <c>ruleset:</c> documents that the pilot modeline
///     (<c>$schema=./dv-rules.schema.json</c>) drives editor completion + validation from. Emits a
///     fresh document from the generated <see cref="CatalogRoot" />, so its view/facet vocabulary never
///     drifts from the engine. The drift gate (<c>CatalogDriftTests</c>) byte-compares a regen
///     against the committed file.
///     <para>
///         The schema carries <b>two explicit shape lists</b> (compiler-plan §9 / spec §7):
///     </para>
///     <list type="bullet">
///         <item>
///             <b>Live in v2.0</b> (schema-valid, loader-accepts): duration literals, role
///             members (<c>victim.*</c>/<c>killer.*</c>/<c>assister.*</c> in expressions),
///             <c>binding:</c> modes (catalog data), <c>off:</c>, <c>actor: any</c>, <c>for_each:</c>.
///         </item>
///         <item>
///             <b>Live in v2.0</b> (un-reserved later): <c>show: as: ticks|seconds|time</c>
///             column display formatting, the <c>"m:ss[.frac]"</c> duration slot scalar, the
///             <c>catalog_version</c>/<c>min_app_version</c> provenance fields, and map-valued
///             <c>define:</c> (a string-keyed lookup table read via <c>ref[key]</c>).
///         </item>
///         <item>
///             <b>Reserved — not yet implemented</b> (schema-present, loader-rejects): the extra
///             bucket <c>per:</c> axes. The team namespaces (<c>round.team.*</c> /
///             <c>round.enemies.*</c> / <c>round.alive.*</c>) and <c>net.*</c>
///             <c>match:</c>/<c>where:</c> payload matching are now <b>live</b>.
///             Bucket composite <c>key:</c>-as-list and named <c>reduce:</c> reducers, and
///             condition source lists (a <c>flag:</c>/<c>highlight:</c> <c>when:</c> authored as a
///             list of predicates = their AND-conjunction) are now <b>live</b>.
///     </list>
/// </summary>
public static class DvRulesSchemaBuilder
{
    private const string ReservedPrefix = "RESERVED - not yet implemented. ";

    /// <summary>Builds the <c>dv-rules.schema.json</c> text from the generated catalog.</summary>
    /// <param name="catalog">The freshly-built catalog (its <c>views</c> family drives the facet enums).</param>
    /// <returns>Deterministic, indented JSON with LF line endings and a trailing newline (drift-comparable).</returns>
    public static string Build(CatalogRoot catalog)
    {
        ArgumentNullException.ThrowIfNull(catalog);

        List<CatalogView> views = catalog.Views.OrderBy(v => v.Name, StringComparer.Ordinal).ToList();

        JsonObject root = new()
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = "dv-rules.schema.json",
            ["title"] = "DemoViewer.NET Rulesets v2",
            ["description"] =
                "Schema for v2 ruleset: documents (docs/rules-v2/rules-v2-spec.md, docs/rules-v2/rules-v2-compiler-plan.md). "
                + "GENERATED by tools/DemoViewer.NET.RulesCatalog from the catalog's views family - edit the "
                + "generator, not this file. Shapes marked 'RESERVED' are present for forward completion but "
                + "the loader rejects them as not-yet-implemented.",
            ["type"] = "object",
            ["required"] = new JsonArray
            {
                "ruleset"
            },
            ["additionalProperties"] = false,
            ["properties"] = TopLevelProperties(),
            ["$defs"] = Defs(catalog, views)
        };

        return root.ToJsonString(new JsonSerializerOptions
            {
                WriteIndented = true
            })
            .ReplaceLineEndings("\n") + "\n";
    }

    private static JsonObject TopLevelProperties() => new()
    {
        ["ruleset"] = new JsonObject
        {
            ["type"] = "string",
            ["description"] = "The ruleset id - unique across the tier's chain/ruleset id namespace (compiler-plan §8)."
        },
        ["title"] = Str("Display title (outside node identity)."),
        ["summary"] = Str("One-line description of what the ruleset detects."),
        ["for"] = new JsonObject
        {
            ["enum"] = new JsonArray
            {
                "match",
                "each_player"
            },
            ["default"] = "match",
            ["markdownDescription"] =
                "Materialization scope. `each_player` instantiates one ruleset per player and binds "
                + "actor-anchored views (kill, damage_dealt, ...) to that player; `match` is one instance "
                + "for the whole demo with no implicit player binding."
        },
        ["enabled"] = new JsonObject
        {
            ["type"] = "boolean",
            ["default"] = true,
            ["description"] = "Set false to disable a shipped ruleset from a user-tier file (compiler-plan §8)."
        },
        ["use"] = new JsonObject
        {
            ["type"] = "array",
            ["items"] = new JsonObject
            {
                ["type"] = "string"
            },
            ["description"] = "Rulesets this file may reference by qualified ruleset.stat (the cross-ruleset allowlist)."
        },
        ["exports"] = new JsonObject
        {
            ["type"] = "array",
            ["items"] = new JsonObject
            {
                ["type"] = "string"
            },
            ["markdownDescription"] =
                "The stat/highlight ids this ruleset exports for cross-ruleset `ruleset.stat` reads. "
                + "Omit to export everything (advisory lint only); list a subset to make the rest private — a "
                + "qualified read of an unexported id is a not-exported error."
        },
        ["params"] = MapOf("#/$defs/param",
            "Named parameters bound to literal values at build (spec §5); reference as params.<name>."),
        ["define"] = MapOf("#/$defs/defineBody",
            "Named triggers, lists, and expressions inlined at their use sites before hashing (spec §5)."),
        ["stats"] = MapOf("#/$defs/stat", "The ruleset's stats, keyed by id (spec §6)."),
        ["highlights"] = MapOf("#/$defs/highlight",
            "Rising-edge achievements: a when: conjunction whose firing produces a timeline event + auto .count."),
        ["show"] = new JsonObject
        {
            ["$ref"] = "#/$defs/show"
        },
        ["catalog_version"] = new JsonObject
        {
            ["type"] = "string",
            ["markdownDescription"] =
                "Provenance field pinning the catalog a blueprint was authored against. Free-form "
                + "human/tooling metadata: accepted and stored, never a build input."
        },
        ["min_app_version"] = new JsonObject
        {
            ["type"] = "string",
            ["markdownDescription"] =
                "Provenance field pinning the minimum app version. Free-form human/tooling metadata: "
                + "accepted and stored, never a build input."
        }
    };

    private static JsonObject Defs(CatalogRoot catalog, List<CatalogView> views)
    {
        JsonObject defs = new()
        {
            ["expression"] = ExpressionDef(),
            ["triggerRef"] = TriggerRefDef(views),
            ["match"] = MatchUnionDef(views),
            ["trigger"] = TriggerDef(),
            ["offTrigger"] = OffTriggerDef(),
            ["param"] = ParamDef(),
            ["defineBody"] = DefineBodyDef(),
            ["stat"] = StatDef(views),
            ["highlight"] = HighlightDef(),
            ["show"] = ShowDef(),
            ["scoreboardEntry"] = ScoreboardEntryDef(),
            ["table"] = TableDef(),
            ["tableColumn"] = TableColumnDef()
        };

        // Per-view match facet enums (compiler-plan §9): one $def per view, referenced by the stat's
        // per-view if/then. Ordered by view name for deterministic output.
        foreach (CatalogView view in views)
        {
            defs[MatchDefName(view.Name)] = PerViewMatchDef(view);
        }

        return defs;
    }

    // ── Expression / trigger vocabulary ────────────────────────────────────────

    private static JsonObject ExpressionDef() => new()
    {
        ["type"] = "string",
        ["markdownDescription"] =
            "A v2 expression (docs/rules-v2/rules-v2-spec.md). Resolves against the slot's scope: `event.*` "
            + "fields, per-player providers `player.*`, B5 role handles `victim.*` / `killer.*` / "
            + "`assister.*` under event views, `round.*` / `match.*` contexts, sibling stats (bare), "
            + "`this`, and cross-ruleset `ruleset.stat`. Duration literals `10s` / `0.5s` / `500ms` are "
            + "live. Closed function set: min, max, abs, contains, startswith. Map-valued `define:` lookups "
            + "`ref[key]` (value | null) are live. B6 team aggregates are live: `round.team.alive` / "
            + "`round.team.players` / `round.enemies.alive` / `round.enemies.players` (int, subject-"
            + "relative alive/connected counts, disconnect-aware), `round.team.equipment` / "
            + "`round.enemies.equipment` (int, freeze-end team economy sums) and `round.alive.in_clutch` "
            + "(bool); read them in `when:` / `while:` / `compute:`."
    };

    private static JsonObject TriggerRefDef(List<CatalogView> views)
    {
        JsonArray examples = [];
        foreach (CatalogView v in views)
        {
            examples.Add(v.Name);
        }

        examples.Add("raw.player_death");
        examples.Add("net.CDemoFileHeader");

        return new JsonObject
        {
            ["type"] = "string",
            ["markdownDescription"] =
                "A trigger source: a curated view (kill, bomb_planted, ...), a same-document `define:` name, "
                + "`raw.<event>` (a wire event with no actor convention), or `net.<Message>` (a net-message "
                + "trigger - both bare triggers and their match:/where: payload matching are live; a "
                + "net trigger's payload fields read under `event.<Field>`, typed from the netMessages catalog).",
            ["examples"] = examples
        };
    }

    private static JsonObject MatchUnionDef(List<CatalogView> views)
    {
        // Union of every view's facets - the base match: shape (per-view precision is added by the
        // stat's per-view if/then). Each facet's markdownDescription names its type + the views that
        // expose it + per-source availability.
        SortedDictionary<string, (string Type, SortedSet<string> Views, string Availability)> facets =
            new(StringComparer.Ordinal);
        foreach (CatalogView view in views)
        {
            foreach (CatalogFacet facet in view.Facets)
            {
                if (!facets.TryGetValue(facet.Name, out (string Type, SortedSet<string> Views, string Availability) acc))
                {
                    acc = (facet.Type, new SortedSet<string>(StringComparer.Ordinal), view.Availability);
                    facets[facet.Name] = acc;
                }

                acc.Views.Add(view.Name);
            }
        }

        JsonObject properties = new();
        foreach ((string name, (string type, SortedSet<string> exposedBy, string availability)) in facets)
        {
            properties[name] = new JsonObject
            {
                ["markdownDescription"] =
                    $"Facet `{name}` (type `{type}`). Exposed by: {string.Join(", ", exposedBy)}. "
                    + $"Availability: {availability}. Value is a unary test (literal / `in list` / comparison / `[lo..hi]`)."
            };
        }

        properties["actor"] = new JsonObject
        {
            ["enum"] = new JsonArray
            {
                "any"
            },
            ["markdownDescription"] =
                "Suppresses the view's implicit per-player actor binding (compiler-plan decision 3). "
                + "`any` is the only value live in v2.0."
        };

        return new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["markdownDescription"] =
                "Structured facet bindings for the triggering view. The valid facet set depends on `on:` - "
                + "see the per-view constraints. On a `net.<Message>` trigger, `match:` is a field-facet "
                + "form over the message payload: each `{ Field: <test> }` lowers to an `event.<Field>` "
                + "where:-conjunct (payload-facet matching).",
            ["properties"] = properties
        };
    }

    private static JsonObject PerViewMatchDef(CatalogView view)
    {
        JsonObject properties = new();
        foreach (CatalogFacet facet in view.Facets.OrderBy(f => f.Name, StringComparer.Ordinal))
        {
            properties[facet.Name] = new JsonObject
            {
                ["markdownDescription"] = $"`{facet.Name}` (type `{facet.Type}`) on view `{view.Name}`."
            };
        }

        properties["actor"] = new JsonObject
        {
            ["enum"] = new JsonArray
            {
                "any"
            },
            ["markdownDescription"] = "Suppress the implicit actor binding (`any` only)."
        };

        List<string> availableOn = view.Profiles
            .Where(p => p.ConcreteEvents.Count > 0)
            .Select(p => p.Profile)
            .OrderBy(p => p, StringComparer.Ordinal)
            .ToList();

        return new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["markdownDescription"] =
                $"match: facets for view `{view.Name}` (event `{view.Event}`, binding `{view.Binding}`). "
                + $"Available on: {(availableOn.Count > 0 ? string.Join(", ", availableOn) : "no profiles")}.",
            ["properties"] = properties
        };
    }

    private static JsonObject TriggerDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["description"] = "The map form of a trigger (a define body or off: block): on/match/where/while.",
        ["properties"] = new JsonObject
        {
            ["on"] = new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef"
            },
            ["match"] = new JsonObject
            {
                ["$ref"] = "#/$defs/match"
            },
            ["where"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression"
            },
            ["while"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] = "A gate: a single round/match context or sibling flag reference."
            }
        }
    };

    private static JsonObject OffTriggerDef() => new()
    {
        ["markdownDescription"] =
            "A deactivate trigger for a flag (live in v2.0): a bare view/define ref, or the map trigger form.",
        ["oneOf"] = new JsonArray
        {
            new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef"
            },
            new JsonObject
            {
                ["$ref"] = "#/$defs/trigger"
            }
        }
    };

    // ── Params & defines ───────────────────────────────────────────────────────

    private static JsonObject ParamDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["required"] = new JsonArray
        {
            "type"
        },
        ["description"] = "A named parameter bound to a literal at build (spec §5).",
        ["properties"] = new JsonObject
        {
            ["type"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "int",
                    "float",
                    "bool",
                    "string",
                    "duration"
                },
                ["markdownDescription"] = "Parameter type. `duration` accepts duration literals (`10s` / `0.5s` / `500ms`)."
            },
            ["default"] = new JsonObject
            {
                ["type"] = new JsonArray
                {
                    "string",
                    "number",
                    "boolean"
                },
                ["description"] = "Default value; must match the declared type."
            },
            ["min"] = new JsonObject
            {
                ["type"] = "number",
                ["description"] = "Inclusive lower bound (numeric types)."
            },
            ["max"] = new JsonObject
            {
                ["type"] = "number",
                ["description"] = "Inclusive upper bound (numeric types)."
            }
        }
    };

    private static JsonObject DefineBodyDef() => new()
    {
        ["markdownDescription"] =
            "A define body: a list (`in` operand), a trigger (map with `on:`), an expression (string), or a "
            + "string-keyed lookup **map** read via `ref[key]` (a miss yields `null`). A map's values must be "
            + "uniform — all numbers or all strings.",
        ["oneOf"] = new JsonArray
        {
            new JsonObject
            {
                ["type"] = "array",
                ["description"] = "A list define: scalar literals used as an `in` operand.",
                ["items"] = new JsonObject
                {
                    ["type"] = new JsonArray
                    {
                        "string",
                        "number",
                        "boolean"
                    }
                }
            },
            new JsonObject
            {
                ["$ref"] = "#/$defs/trigger"
            },
            new JsonObject
            {
                ["$ref"] = "#/$defs/expression"
            },
            new JsonObject
            {
                ["type"] = "object",
                ["markdownDescription"] =
                    "A map define: a string-keyed lookup table (`weapon_class: {ak47: rifle, awp: sniper}`), "
                    + "read via `ref[key]` → value | null. Values must be all numbers or all strings.",
                ["additionalProperties"] = new JsonObject
                {
                    ["type"] = new JsonArray
                    {
                        "string",
                        "number"
                    }
                }
            }
        }
    };

    // ── Stat ───────────────────────────────────────────────────────────────────

    private static JsonObject StatDef(List<CatalogView> views)
    {
        JsonObject properties = new()
        {
            ["flag"] = new JsonObject
            {
                ["markdownDescription"] =
                    "`flag: true` (a bool set by `on:`, optionally cleared by `off:`) or `flag: { when: <expr> }` "
                    + "(a bool auto-computed from sibling stats).",
                ["oneOf"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["type"] = "boolean"
                    },
                    new JsonObject
                    {
                        ["type"] = "object",
                        ["additionalProperties"] = false,
                        ["required"] = new JsonArray
                        {
                            "when"
                        },
                        ["properties"] = new JsonObject
                        {
                            ["when"] = WhenSlot()
                        }
                    }
                }
            },
            ["count"] = new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef",
                ["markdownDescription"] = "A counter incremented on each fire of the referenced trigger or flag rising edge."
            },
            ["sum"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] = "A running total: the value selector is added on each triggering event."
            },
            ["capture"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] = "Captures a value on each triggering event; `keep:` chooses first / last / list / min / max."
            },
            ["compute"] = new JsonObject
            {
                ["markdownDescription"] =
                    "A formula over sibling stats. `compute: \"<expr>\"` evaluates once at round end. "
                    + "`compute: { value: \"<expr>\", live: true }` opts into live cadence: "
                    + "it re-evaluates during the round as its reads change, so downstream reads and the "
                    + "timeline see the current value, not only the round-end one. A live compute recomputes "
                    + "at most once per evaluated message (its value is memoized between recomputes).",
                ["oneOf"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["$ref"] = "#/$defs/expression"
                    },
                    new JsonObject
                    {
                        ["type"] = "object",
                        ["additionalProperties"] = false,
                        ["required"] = new JsonArray
                        {
                            "value"
                        },
                        ["properties"] = new JsonObject
                        {
                            ["value"] = new JsonObject
                            {
                                ["$ref"] = "#/$defs/expression",
                                ["markdownDescription"] = "The formula over sibling stats."
                            },
                            ["live"] = new JsonObject
                            {
                                ["type"] = "boolean",
                                ["markdownDescription"] =
                                    "Opt into live cadence: re-evaluate the formula during the round as its "
                                    + "reads change, instead of once at round end. Defaults to false (round-end)."
                            }
                        }
                    }
                }
            },
            ["tally"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] =
                    "A threshold tally: reads a sibling value source (the kind value) and, at round end, increments "
                    + "the first `thresholds:` bucket whose `min` the source meets (highest min first)."
            },
            ["streak"] = new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef",
                ["markdownDescription"] =
                    "A windowed streak counter over the referenced trigger's events: consecutive events within "
                    + "`window:` extend a streak; a streak of at least `min_streak:` increments the count."
            },
            ["bucket"] = new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef",
                ["markdownDescription"] =
                    "A per-key counter over the referenced trigger's events, keyed by `key:` (a single "
                    + "expression or a list of them → a composite/tuple key). The `reduce:` reducer folds each "
                    + "key: `count` (+1 per event, the default without `value:`), or over a `value:` amount "
                    + "`sum` (the default with `value:`), `min`, `max`, `last`, or `first`. Match-scoped and "
                    + "sampled per-game."
            },
            ["rate"] = new JsonObject
            {
                ["type"] = "object",
                ["additionalProperties"] = false,
                ["required"] = new JsonArray
                {
                    "of",
                    "per"
                },
                ["markdownDescription"] =
                    "A per-key ratio (G3) over two same-keyed sibling `bucket:` stats: `of` (numerator) / "
                    + "`per` (denominator), evaluated per denominator key. Output iterates the DENOMINATOR "
                    + "key set (a rate is defined only where the population base exists); a numerator-missing "
                    + "key is `0 / denom = 0.0` (a real row); a denominator key that is 0 is skipped "
                    + "(undefined ratio). Both buckets must key on identical `key:` parts. Match-scoped "
                    + "and sampled per-game.",
                ["properties"] = new JsonObject
                {
                    ["of"] = new JsonObject
                    {
                        ["type"] = "string",
                        ["markdownDescription"] = "The numerator bucket stat id (per-key numerators)."
                    },
                    ["per"] = new JsonObject
                    {
                        ["type"] = "string",
                        ["markdownDescription"] =
                            "The denominator bucket stat id — its key set is the output population base."
                    }
                }
            },
            ["thresholds"] = new JsonObject
            {
                ["type"] = "array",
                ["items"] = new JsonObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = false,
                    ["required"] = new JsonArray
                    {
                        "min",
                        "target"
                    },
                    ["properties"] = new JsonObject
                    {
                        ["min"] = new JsonObject
                        {
                            ["type"] = new JsonArray
                            {
                                "integer",
                                "string"
                            },
                            ["description"] = "Inclusive minimum source value that activates this bucket - an "
                                              + "integer literal, or a `params.<name>` reference to a bound int param "
                                              + "(resolved to its literal value before hashing)."
                        },
                        ["target"] = new JsonObject
                        {
                            ["type"] = "string",
                            ["description"] = "Id of the counter node this bucket increments when it wins."
                        }
                    }
                },
                ["markdownDescription"] = "tally: ordered `{ min, target }` threshold buckets (the highest matching min wins)."
            },
            ["window"] = new JsonObject
            {
                ["type"] = new JsonArray
                {
                    "integer",
                    "string"
                },
                ["markdownDescription"] =
                    "streak: the maximum gap between consecutive events for the streak to extend - an integer tick "
                    + "count, a duration literal (`10s`, `640ms`), or the `\"m:ss[.frac]\"` clock form "
                    + "(`\"1:30\"` = 90s). Durations fold at the context tick rate. Defaults to 640 ticks."
            },
            ["min_streak"] = new JsonObject
            {
                ["type"] = "integer",
                ["minimum"] = 1,
                ["markdownDescription"] = "streak: the minimum streak length that counts as a completed streak. Defaults to 2."
            },
            ["key"] = new JsonObject
            {
                ["oneOf"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["$ref"] = "#/$defs/expression"
                    },
                    new JsonObject
                    {
                        ["type"] = "array",
                        ["minItems"] = 1,
                        ["items"] = new JsonObject
                        {
                            ["$ref"] = "#/$defs/expression"
                        }
                    }
                },
                ["markdownDescription"] =
                    "bucket: the key selecting the per-event bucket, e.g. `event.Weapon` (must yield a string). "
                    + "A list of expressions forms an ordered composite/tuple key, e.g. "
                    + "`[event.Weapon, event.WeaponItemId]` (order is identity-bearing)."
            },
            ["value"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] =
                    "bucket: the per-event numeric amount the reducer folds into the key, e.g. "
                    + "`enrich.hurt.capped_damage`. Required by `sum`/`min`/`max`/`last`/`first`; omit it for a "
                    + "`count` bucket (+1 per event). Defaults the reducer to `sum` when present, `count` when absent."
            },
            ["reduce"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "sum",
                    "count",
                    "min",
                    "max",
                    "last",
                    "first"
                },
                ["markdownDescription"] =
                    "bucket: the per-key reducer. `count` (+1 per event, no `value:`) or, over a `value:` amount, "
                    + "`sum` / `min` / `max` / `last` / `first`. Defaults to `sum` when `value:` is present, else `count`."
            },
            ["per"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "round",
                    "match"
                },
                ["default"] = "round",
                ["description"] = "Reset scope: round-scoped (reset each round) or match-scoped."
            },
            ["keep"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "first",
                    "last",
                    "list",
                    "min",
                    "max"
                },
                ["markdownDescription"] = "Capture keep policy (only valid under `capture:`). `list` yields a collection; `min` / `max` keep the running extremum of a numeric value over the window."
            },
            ["on"] = new JsonObject
            {
                ["$ref"] = "#/$defs/triggerRef"
            },
            ["match"] = new JsonObject
            {
                ["$ref"] = "#/$defs/match"
            },
            ["where"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression"
            },
            ["while"] = new JsonObject
            {
                ["$ref"] = "#/$defs/expression",
                ["markdownDescription"] = "A gate: fire only while a round/match context or sibling flag is active."
            },
            ["off"] = new JsonObject
            {
                ["$ref"] = "#/$defs/offTrigger"
            },
            ["label"] = Str("Display label (outside node identity)."),
            ["format"] = Str(
                "compute: display format — a .NET numeric format string (e.g. `F2`, `F0`) applied when "
                + "rendering the computed value. Defaults to `F1`. Presentation only: outside node identity "
                + "(two computes differing only in `format:` dedup)."),
            ["for_each"] = new JsonObject
            {
                ["type"] = "object",
                ["additionalProperties"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = new JsonObject
                    {
                        ["type"] = new JsonArray
                        {
                            "string",
                            "number",
                            "boolean"
                        }
                    }
                },
                ["markdownDescription"] =
                    "Template expansion: multiplies the stat over each axis, substituting `{key}` into ids, "
                    + "expressions, labels, and titles (live in v2.0)."
            }
        };

        JsonArray allOf = new()
        {
            // keep: only under capture (spec §1.3 structural rule).
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "keep"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "capture"
                    }
                }
            },
            // tally requires thresholds and vice versa; thresholds are tally-only.
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "tally"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "thresholds"
                    }
                }
            },
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "thresholds"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "tally"
                    }
                }
            },
            // bucket requires key and vice versa; key: is bucket-only.
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "bucket"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "key"
                    }
                }
            },
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "key"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "bucket"
                    }
                }
            },
            // value: (the reducer's per-event amount) is bucket-only; it does not require key on its own
            // (bucket already requires key above), but it is meaningless outside a bucket.
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "value"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "bucket"
                    }
                }
            },
            // reduce: (the named per-key reducer) is bucket-only.
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "reduce"
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "bucket"
                    }
                }
            },
            // window: / min_streak: are streak-only.
            new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["anyOf"] = new JsonArray
                    {
                        new JsonObject
                        {
                            ["required"] = new JsonArray
                            {
                                "window"
                            }
                        },
                        new JsonObject
                        {
                            ["required"] = new JsonArray
                            {
                                "min_streak"
                            }
                        }
                    }
                },
                ["then"] = new JsonObject
                {
                    ["required"] = new JsonArray
                    {
                        "streak"
                    }
                }
            }
        };

        // Per-view match facet constraint: when the trigger source is a known view - named by `on:`
        // for most kinds, or by the `count:` value for a count stat - match: must conform to that
        // view's facet enum (compiler-plan §9 per-view facet enums).
        foreach (CatalogView view in views)
        {
            allOf.Add(new JsonObject
            {
                ["if"] = new JsonObject
                {
                    ["anyOf"] = new JsonArray
                    {
                        new JsonObject
                        {
                            ["properties"] = new JsonObject
                            {
                                ["on"] = new JsonObject
                                {
                                    ["const"] = view.Name
                                }
                            },
                            ["required"] = new JsonArray
                            {
                                "on"
                            }
                        },
                        new JsonObject
                        {
                            ["properties"] = new JsonObject
                            {
                                ["count"] = new JsonObject
                                {
                                    ["const"] = view.Name
                                }
                            },
                            ["required"] = new JsonArray
                            {
                                "count"
                            }
                        }
                    }
                },
                ["then"] = new JsonObject
                {
                    ["properties"] = new JsonObject
                    {
                        ["match"] = new JsonObject
                        {
                            ["$ref"] = $"#/$defs/{MatchDefName(view.Name)}"
                        }
                    }
                }
            });
        }

        return new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["markdownDescription"] =
                "One stat = one graph node. Declare exactly one kind: flag / count / sum / capture / compute / "
                + "tally / streak / bucket / rate.",
            ["properties"] = properties,
            ["allOf"] = allOf,
            ["defaultSnippets"] = StatSnippets()
        };
    }

    private static JsonArray StatSnippets() => new()
    {
        Snippet("count on a view", "A per-round counter over a curated view.",
            new JsonObject
            {
                ["count"] = "kill",
                ["match"] = new JsonObject
                {
                    ["enemy"] = true
                },
                ["per"] = "round"
            }),
        Snippet("capture first", "Capture the first value seen this round.",
            new JsonObject
            {
                ["capture"] = "event.tick",
                ["on"] = "bomb_planted",
                ["keep"] = "first",
                ["per"] = "round"
            }),
        Snippet("flag with on/off", "A bool set by one event and cleared by another.",
            new JsonObject
            {
                ["flag"] = true,
                ["on"] = "bomb_planted",
                ["off"] = "bomb_defused",
                ["per"] = "round"
            }),
        Snippet("compute at round end", "A round-end formula over sibling stats.",
            new JsonObject
            {
                ["compute"] = "kills / max(deaths, 1)",
                ["per"] = "match"
            }),
        Snippet("threshold tally", "Tally a sibling value into min/target buckets at round end.",
            new JsonObject
            {
                ["tally"] = "round_kills",
                ["thresholds"] = new JsonArray
                {
                    new JsonObject
                    {
                        ["min"] = 3,
                        ["target"] = "multi3"
                    },
                    new JsonObject
                    {
                        ["min"] = 2,
                        ["target"] = "multi2"
                    }
                },
                ["per"] = "match"
            }),
        Snippet("windowed streak", "Count streaks of events within a tick window.",
            new JsonObject
            {
                ["streak"] = "kill",
                ["window"] = 640,
                ["min_streak"] = 2,
                ["per"] = "match"
            }),
        Snippet("per-key bucket", "A per-key counter (e.g. per weapon).",
            new JsonObject
            {
                ["bucket"] = "kill",
                ["key"] = "event.Weapon",
                ["per"] = "match"
            }),
        Snippet("per-key sum bucket", "A per-key SUM (e.g. damage per weapon).",
            new JsonObject
            {
                ["bucket"] = "damage_dealt",
                ["key"] = "event.Weapon",
                ["value"] = "enrich.hurt.capped_damage",
                ["match"] = new JsonObject
                {
                    ["enemy"] = true
                },
                ["per"] = "match"
            }),
        Snippet("per-key rate", "A per-key ratio of two same-keyed buckets (e.g. headshot % per weapon).",
            new JsonObject
            {
                ["rate"] = new JsonObject
                {
                    ["of"] = "hs_kills_by_weapon",
                    ["per"] = "kills_by_weapon"
                },
                ["per"] = "match"
            })
    };

    // ── Highlight / show ───────────────────────────────────────────────────────

    private static JsonObject HighlightDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["required"] = new JsonArray
        {
            "when",
            "title"
        },
        ["markdownDescription"] =
            "A rising-edge achievement: when `when:` first becomes true it emits a timeline event and increments "
            + "an auto match-scoped `<id>.count`.",
        ["properties"] = new JsonObject
        {
            ["when"] = WhenSlot(),
            ["per"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "round",
                    "match"
                },
                ["default"] = "round",
                ["description"] = "The rising-edge scope (the .count node is always match-scoped)."
            },
            ["title"] = new JsonObject
            {
                ["type"] = "string",
                ["markdownDescription"] = "A `{hole}` template rendered on fire, e.g. `{player.name} - {kills} kills`."
            },
            ["score"] = new JsonObject
            {
                ["type"] = "integer",
                ["minimum"] = 0,
                ["maximum"] = 100,
                ["default"] = 50,
                ["description"] =
                    "Base ranking weight (0-100) folding rarity and coolness; the reel surfaces "
                    + "higher-scored firings first. Defaults to 50."
            },
            ["kind"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "highlight",
                    "funny",
                    "lowlight",
                    "hidden"
                },
                ["default"] = "highlight",
                ["description"] =
                    "The editorial track this firing belongs to: a skill highlight (default), a funny "
                    + "moment, or a lowlight; each routes into its reel. Use 'hidden' for a counting-only "
                    + "round flag whose .count feeds a rating/stat (e.g. a KAST round) but which is never "
                    + "shown in any reel."
            },
            ["group"] = new JsonObject
            {
                ["type"] = "string",
                ["markdownDescription"] =
                    "A supersession family. Firings that share a `group:` are collapsed at the surfacing "
                    + "layer to the single highest-`score:` one per player+round, so a tiered family "
                    + "(e.g. `3K`/`4K`/`ace` all tagged `group: multikill`) surfaces only its top tier "
                    + "instead of every threshold it crossed. Omit for a standalone highlight."
            },
            ["for_each"] = new JsonObject
            {
                ["type"] = "object",
                ["additionalProperties"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = new JsonObject
                    {
                        ["type"] = new JsonArray
                        {
                            "string",
                            "number",
                            "boolean"
                        }
                    }
                }
            }
        },
        ["defaultSnippets"] = new JsonArray
        {
            Snippet("highlight", "A per-round achievement.",
                new JsonObject
                {
                    ["when"] = "kills >= 3",
                    ["per"] = "round",
                    ["title"] = "{player.name} - {kills} kills (round {round.number})"
                })
        }
    };

    private static JsonObject ShowDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["description"] = "The single surfacing block (compiler-plan §7): scoreboard columns + custom export tables.",
        ["properties"] = new JsonObject
        {
            ["scoreboard"] = new JsonObject
            {
                ["type"] = "array",
                ["items"] = new JsonObject
                {
                    ["$ref"] = "#/$defs/scoreboardEntry"
                },
                ["description"] = "Stat/highlight refs surfaced as scoreboard columns."
            },
            ["tables"] = MapOf("#/$defs/table", "Custom export tables keyed by name.")
        }
    };

    private static JsonObject ScoreboardEntryDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["required"] = new JsonArray
        {
            "stat"
        },
        ["properties"] = new JsonObject
        {
            ["stat"] = new JsonObject
            {
                ["type"] = "string",
                ["markdownDescription"] =
                    "A stat id, or a highlight ref (`<id>` / `<id>.count`) which surfaces the match-scoped count."
            },
            ["label"] = Str("Column header (defaults to the stat ref)."),
            ["group"] = Str("Display group the UI clusters columns under."),
            ["boards"] = new JsonObject
            {
                ["type"] = "array",
                ["items"] = new JsonObject
                {
                    ["enum"] = new JsonArray
                    {
                        "round",
                        "match"
                    }
                },
                ["markdownDescription"] = "Override the per:-inferred board(s). Omit to default from the stat's scope."
            },
            ["as"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "ticks",
                    "seconds",
                    "time"
                },
                ["markdownDescription"] =
                    "Display formatting for a tick-valued column: `ticks` = raw integer ticks, "
                    + "`seconds` = ticks / tick-rate, `time` = `m:ss` at the tick rate. Omit for the raw value."
            }
        }
    };

    private static JsonObject TableDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["required"] = new JsonArray
        {
            "per",
            "columns"
        },
        ["properties"] = new JsonObject
        {
            ["per"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "player_round",
                    "player_match",
                    "match"
                },
                ["description"] = "The export dimension (the closed table registry). `player_round` / "
                                  + "`player_match` are per-player (for: each_player); `match` is a single "
                                  + "match-level row (for: match)."
            },
            ["columns"] = new JsonObject
            {
                ["type"] = "array",
                ["items"] = new JsonObject
                {
                    ["$ref"] = "#/$defs/tableColumn"
                }
            }
        }
    };

    private static JsonObject TableColumnDef() => new()
    {
        ["type"] = "object",
        ["additionalProperties"] = false,
        ["required"] = new JsonArray
        {
            "stat"
        },
        ["properties"] = new JsonObject
        {
            ["stat"] = Str("A stat id, or a highlight ref binding to its per-round fired state."),
            ["label"] = Str("Column header (defaults to the stat ref)."),
            ["as"] = new JsonObject
            {
                ["enum"] = new JsonArray
                {
                    "ticks",
                    "seconds",
                    "time"
                },
                ["markdownDescription"] =
                    "Display formatting for a tick-valued column: `ticks` = raw integer ticks, "
                    + "`seconds` = ticks / tick-rate, `time` = `m:ss` at the tick rate. Omit for the raw value."
            }
        }
    };

    // ── Small factory helpers ──────────────────────────────────────────────────

    private static JsonObject Str(string description) => new()
    {
        ["type"] = "string",
        ["description"] = description
    };

    /// <summary>
    ///     The <c>when:</c> slot on a <c>flag:</c> stat or a <c>highlight:</c> (condition source
    ///     lists): a single boolean expression, or a <b>list</b> of expressions whose meaning is the
    ///     AND-conjunction of its items — <c>[a, b]</c> ≡ <c>(a) and (b)</c>. The list form is pure
    ///     authoring sugar (identical resolved AST, identity hash, and lowering to the joined string);
    ///     a single-item list equals the bare expression.
    /// </summary>
    private static JsonObject WhenSlot() => new()
    {
        ["markdownDescription"] =
            "A boolean condition. Either a single expression, or a **list** of expressions read as their "
            + "AND-conjunction (`[a, b]` ≡ `(a) and (b)`) — a convenience for declaring each input on its "
            + "own line. A single-item list equals the bare expression.",
        ["oneOf"] = new JsonArray
        {
            new JsonObject
            {
                ["$ref"] = "#/$defs/expression"
            },
            new JsonObject
            {
                ["type"] = "array",
                ["minItems"] = 1,
                ["items"] = new JsonObject
                {
                    ["$ref"] = "#/$defs/expression"
                }
            }
        }
    };

    private static JsonObject MapOf(string itemRef, string description) => new()
    {
        ["type"] = "object",
        ["description"] = description,
        ["additionalProperties"] = new JsonObject
        {
            ["$ref"] = itemRef
        }
    };

    /// <summary>Wraps a schema node with the standard RESERVED annotation (schema-present, loader-rejected).</summary>
    private static JsonObject Reserved(JsonObject node, string why)
    {
        node["markdownDescription"] = ReservedPrefix + why;
        node["deprecated"] = true;
        return node;
    }

    private static JsonObject Snippet(string label, string description, JsonObject body) => new()
    {
        ["label"] = label,
        ["description"] = description,
        ["body"] = body
    };

    private static string MatchDefName(string viewName) => $"match_{viewName}";
}
